// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Coordinates } from './coordinates';

/**
* A JSON object containing the receiver’s location information.
*/
export class Address {
    /**
    * The delivery address\' unit number.
    */
    'unitNumber'?: string;
    /**
    * Instructions for the delivery.
    */
    'deliveryInstruction'?: string;
    /**
    * POI source
    */
    'poiSource'?: Address.PoiSourceEnum;
    /**
    * POI ID, empty when poiSource is GRAB.
    */
    'poiID'?: string;
    /**
    * The delivery address containing street name, city, postal code, and country. Has value only when poiSource is `GRAB`.
    */
    'address'?: string;
    /**
    * The postcode of the delivery address. Has value only when poiSource is `GRAB`.
    */
    'postcode'?: string;
    'coordinates'?: Coordinates;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "unitNumber",
            "baseName": "unitNumber",
            "type": "string"
        },
        {
            "name": "deliveryInstruction",
            "baseName": "deliveryInstruction",
            "type": "string"
        },
        {
            "name": "poiSource",
            "baseName": "poiSource",
            "type": "Address.PoiSourceEnum"
        },
        {
            "name": "poiID",
            "baseName": "poiID",
            "type": "string"
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "string"
        },
        {
            "name": "postcode",
            "baseName": "postcode",
            "type": "string"
        },
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "Coordinates"
        }    ];

    static getAttributeTypeMap() {
        return Address.attributeTypeMap;
    }
}

export namespace Address {
    export enum PoiSourceEnum {
        Grab = <any> 'GRAB',
        Google = <any> 'GOOGLE',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
