// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Price configuration (in minor unit) for different service, order type and channel combination. If a service type does not have a specified price, it will utilize the default price of the item. Refer [Service Based Menu](#section/Service-Based-Menu). 
*/
export class AdvancedPricing {
    /**
    * Service type: `Delivery`, Order type: `Instant`, Channel: `Grab App` 
    */
    'Delivery_OnDemand_GrabApp'?: number;
    /**
    * Service type: `Delivery`, Order type: `Scheduled`, Channel: `Grab App` 
    */
    'Delivery_Scheduled_GrabApp'?: number;
    /**
    * Service type: `Self Pick Up`, Order type: `Instant`, Channel: `Grab App` 
    */
    'SelfPickUp_OnDemand_GrabApp'?: number;
    /**
    * Service type: `Dine In`, Order type: `Instant`, Channel: `Grab App` 
    */
    'DineIn_OnDemand_GrabApp'?: number;
    /**
    * Service type: `Delivery`, Order type: `Instant`, Channel: `Store Front` 
    */
    'Delivery_OnDemand_StoreFront'?: number;
    /**
    * Service type: `Delivery`, Order type: `Scheduled`, Channel: `Store Front` 
    */
    'Delivery_Scheduled_StoreFront'?: number;
    /**
    * Service type: `Self Pick Up`, Order type: `Instant`, Channel: `Store Front` 
    */
    'SelfPickUp_OnDemand_StoreFront'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Delivery_OnDemand_GrabApp",
            "baseName": "Delivery_OnDemand_GrabApp",
            "type": "number"
        },
        {
            "name": "Delivery_Scheduled_GrabApp",
            "baseName": "Delivery_Scheduled_GrabApp",
            "type": "number"
        },
        {
            "name": "SelfPickUp_OnDemand_GrabApp",
            "baseName": "SelfPickUp_OnDemand_GrabApp",
            "type": "number"
        },
        {
            "name": "DineIn_OnDemand_GrabApp",
            "baseName": "DineIn_OnDemand_GrabApp",
            "type": "number"
        },
        {
            "name": "Delivery_OnDemand_StoreFront",
            "baseName": "Delivery_OnDemand_StoreFront",
            "type": "number"
        },
        {
            "name": "Delivery_Scheduled_StoreFront",
            "baseName": "Delivery_Scheduled_StoreFront",
            "type": "number"
        },
        {
            "name": "SelfPickUp_OnDemand_StoreFront",
            "baseName": "SelfPickUp_OnDemand_StoreFront",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AdvancedPricing.attributeTypeMap;
    }
}

