// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuEntityError } from './menuEntityError';

export class BatchUpdateMenuResponse {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * The status of this request.
    */
    'status'?: BatchUpdateMenuResponse.StatusEnum;
    /**
    * The error messages when batch update menu record was partial success/fail. `null` when the request was success.
    */
    'errors'?: Array<MenuEntityError> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "BatchUpdateMenuResponse.StatusEnum"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<MenuEntityError>"
        }    ];

    static getAttributeTypeMap() {
        return BatchUpdateMenuResponse.attributeTypeMap;
    }
}

export namespace BatchUpdateMenuResponse {
    export enum StatusEnum {
        Success = <any> 'success',
        PartialSuccess = <any> 'partial success',
        Fail = <any> 'fail',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
