// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuEntity } from './menuEntity';

/**
* Information about the GrabFood client updating their food menu. 
*/
export class BatchUpdateMenuItem {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID': string;
    /**
    * The record type that you want to update.
    */
    'field': BatchUpdateMenuItem.FieldEnum;
    /**
    * The items in an array of JSON Object. 
    */
    'menuEntities'?: Array<MenuEntity>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "BatchUpdateMenuItem.FieldEnum"
        },
        {
            "name": "menuEntities",
            "baseName": "menuEntities",
            "type": "Array<MenuEntity>"
        }    ];

    static getAttributeTypeMap() {
        return BatchUpdateMenuItem.attributeTypeMap;
    }
}

export namespace BatchUpdateMenuItem {
    export enum FieldEnum {
        Item = <any> 'ITEM',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
