// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignConditions } from './campaignConditions';
import { CampaignDiscount } from './campaignDiscount';
import { CampaignQuotas } from './campaignQuotas';

/**
* A JSON object containing the campaign details for a merchant. Only campaigns that are funded by merchants will be sent.
*/
export class Campaign {
    /**
    * The campaign\'s ID.
    */
    'id': string;
    /**
    * The party who created the campaign. Can be created by partners via API, merchants via the merchant app or Grab.
    */
    'createdBy': Campaign.CreatedByEnum;
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID': string;
    /**
    * The campaign\'s name.
    */
    'name': string;
    'quotas'?: CampaignQuotas;
    'conditions'?: CampaignConditions;
    'discount'?: CampaignDiscount;
    /**
    * Specify the tag for custom bundle offer campaign. Only whitelisted partner is supported as of now.
    */
    'customTag'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "Campaign.CreatedByEnum"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "quotas",
            "baseName": "quotas",
            "type": "CampaignQuotas"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "CampaignConditions"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "CampaignDiscount"
        },
        {
            "name": "customTag",
            "baseName": "customTag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Campaign.attributeTypeMap;
    }
}

export namespace Campaign {
    export enum CreatedByEnum {
        Grab = <any> 'Grab',
        Merchant = <any> 'Merchant',
        Partner = <any> 'Partner',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
