// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The quotas/limits for a particular campaign.
*/
export class CampaignQuotas {
    /**
    * The maximum number of redemptions. Default is unlimited if unspecified. 
    */
    'totalCount'?: number;
    /**
    * The maximum number of redemptions per user. Default is unlimited if unspecified.
    */
    'totalCountPerUser'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number"
        },
        {
            "name": "totalCountPerUser",
            "baseName": "totalCountPerUser",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CampaignQuotas.attributeTypeMap;
    }
}

