// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkingHour } from './workingHour';

/**
* The conditions to apply to a campaign.
*/
export class CampaignConditions {
    /**
    * The campaign\'s start time in UTC format. For example, 2021-09-23T03:30:00Z means 2021-09-23 11:30:00 (UTC +08:00).
    */
    'startTime': Date;
    /**
    * The campaign\'s end time in UTC format.
    */
    'endTime': Date;
    /**
    * The type of eater eligible for the campaign.  * `all` - campaign will be applied to everyone. No limitation on campaign type. * `new` - campaign will be applied to consumers who have not ordered from this store in the last three months. Only applicable to **order-level** campaign. 
    */
    'eaterType': CampaignConditions.EaterTypeEnum;
    /**
    * The minimum basket amount to be eligible for the campaign. Only applicable to **order-level** campaign but not to item-level discount campaign.
    */
    'minBasketAmount'?: number;
    /**
    * Specify the bundle quantity for bundle offer campaign.
    */
    'bundleQuantity'?: number;
    'workingHour'?: WorkingHour;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date"
        },
        {
            "name": "eaterType",
            "baseName": "eaterType",
            "type": "CampaignConditions.EaterTypeEnum"
        },
        {
            "name": "minBasketAmount",
            "baseName": "minBasketAmount",
            "type": "number"
        },
        {
            "name": "bundleQuantity",
            "baseName": "bundleQuantity",
            "type": "number"
        },
        {
            "name": "workingHour",
            "baseName": "workingHour",
            "type": "WorkingHour"
        }    ];

    static getAttributeTypeMap() {
        return CampaignConditions.attributeTypeMap;
    }
}

export namespace CampaignConditions {
    export enum EaterTypeEnum {
        All = <any> 'all',
        New = <any> 'new',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
