// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The scope level for a particular campaign.
*/
export class CampaignScope {
    /**
    * The scope type for this campaign.  * `order` - order level campaign. * `items` - item level campaign or bundle offer.  * `category` - category level campaign where all items within applies the same discount. 
    */
    'type': CampaignScope.TypeEnum;
    /**
    * The list of item IDs in the partner\'s database applicable for discount when `discount.scope.type` is `items` (or category IDs for `category`).  One and only 1 item supported when `discount.type` is: - `freeItem` - `bundleSameNet` - `bundleSamePercentage` - `bundleSameFixPrice`  Minimum 2 - Maximum 20 items supported when `discount.type` is: - `bundleDiffNet` - `bundleDiffPercentage` - `bundleDiffFixPrice` 
    */
    'objectIDs'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignScope.TypeEnum"
        },
        {
            "name": "objectIDs",
            "baseName": "objectIDs",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return CampaignScope.attributeTypeMap;
    }
}

export namespace CampaignScope {
    export enum TypeEnum {
        Order = <any> 'order',
        Items = <any> 'items',
        Category = <any> 'category',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
