// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignScope } from './campaignScope';

/**
* The discount detail for a particular campaign when conditions are satisfied.
*/
export class CampaignDiscount {
    /**
    * The type of discount 
    */
    'type': CampaignDiscount.TypeEnum;
    /**
    * The maximum discount dollar amount. It is **not required** and will be ignored when the `discount.type` is: - `net` - `delivery` - `freeItem` - `bundleSameNet` - `bundleSamePercentage` - `bundleSameFixPrice` - `bundleDiffNet` - `bundleDiffPercentage` - `bundleDiffFixPrice` 
    */
    'cap'?: number;
    /**
    * Specify the discount amount. Decimal number is not supported For VN, ID and TH. For example, `10.5` is not allowed and it should be `10.0`. * Dollar amount value when `discount.type` is `net`, `delivery`, `bundleSameNet`, `bundleSameFixPrice`, `bundleDiffNet`, `bundleDiffFixPrice`. * Percentage value (0-100) when `discount.type` is `percentage`, `bundleSamePercentage`, `bundleDiffPercentage`. * **Not required** when `discount.type` is `freeItem`. 
    */
    'value'?: number;
    'scope': CampaignScope;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CampaignDiscount.TypeEnum"
        },
        {
            "name": "cap",
            "baseName": "cap",
            "type": "number"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "CampaignScope"
        }    ];

    static getAttributeTypeMap() {
        return CampaignDiscount.attributeTypeMap;
    }
}

export namespace CampaignDiscount {
    export enum TypeEnum {
        Net = <any> 'net',
        Percentage = <any> 'percentage',
        Delivery = <any> 'delivery',
        FreeItem = <any> 'freeItem',
        BundleSameNet = <any> 'bundleSameNet',
        BundleSamePercentage = <any> 'bundleSamePercentage',
        BundleSameFixPrice = <any> 'bundleSameFixPrice',
        BundleDiffNet = <any> 'bundleDiffNet',
        BundleDiffPercentage = <any> 'bundleDiffPercentage',
        BundleDiffFixPrice = <any> 'bundleDiffFixPrice',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
