// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The cancel code for a specific cancel reason.
*/
export enum CancelCode {
    NUMBER_1001 = <any> 1001,
    NUMBER_1002 = <any> 1002,
    NUMBER_1003 = <any> 1003,
    NUMBER_1004 = <any> 1004,
    NUMBER_unknown_default_open_api = <any> 11184809
}
