// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The type of the order cancellation limit.
*/
export enum CancelOrderLimitType {
    NotApproachingLimit = <any> 'not approaching limit',
    ApproachingTheDailyLimit = <any> 'approaching the daily limit',
    ApproachingTheWeeklyLimit = <any> 'approaching the weekly limit',
    ApproachingTheMonthlyLimit = <any> 'approaching the monthly limit',
    Empty = <any> '',
    UnknownDefaultOpenApi = <any> '11184809'
}
