// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelCode } from './cancelCode';

/**
* This request cancels an order on GrabFood. 
*/
export class CancelOrderRequest {
    /**
    * The order\'s ID that is returned from GrabFood. Refer to FAQs for more details about [orderID and shortOrderNumber](#section/Order/What\'s-the-difference-between-orderID-and-shortOrderNumber).
    */
    'orderID': string;
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID': string;
    'cancelCode': CancelCode;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderID",
            "baseName": "orderID",
            "type": "string"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "cancelCode",
            "baseName": "cancelCode",
            "type": "CancelCode"
        }    ];

    static getAttributeTypeMap() {
        return CancelOrderRequest.attributeTypeMap;
    }
}

export namespace CancelOrderRequest {
}
