// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CancelOrderLimitType } from './cancelOrderLimitType';
import { CancelReason } from './cancelReason';

/**
* 
*/
export class CheckOrderCancelableResponse {
    /**
    * The boolean value to indicate whether an order can be cancelled.
    */
    'cancelAble'?: boolean;
    /**
    * The reason for the order to be non-cancelable.
    */
    'nonCancellationReason'?: CheckOrderCancelableResponse.NonCancellationReasonEnum;
    'limitType'?: CancelOrderLimitType;
    /**
    * The remaining cancellation quota for the merchant. A value is only returned when the nearest remaining cancellation limit is approaching, else it returns 0.
    */
    'limitTimes'?: number;
    /**
    * An array of cancel order reasons JSON objects.
    */
    'cancelReasons'?: Array<CancelReason>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelAble",
            "baseName": "cancelAble",
            "type": "boolean"
        },
        {
            "name": "nonCancellationReason",
            "baseName": "nonCancellationReason",
            "type": "CheckOrderCancelableResponse.NonCancellationReasonEnum"
        },
        {
            "name": "limitType",
            "baseName": "limitType",
            "type": "CancelOrderLimitType"
        },
        {
            "name": "limitTimes",
            "baseName": "limitTimes",
            "type": "number"
        },
        {
            "name": "cancelReasons",
            "baseName": "cancelReasons",
            "type": "Array<CancelReason>"
        }    ];

    static getAttributeTypeMap() {
        return CheckOrderCancelableResponse.attributeTypeMap;
    }
}

export namespace CheckOrderCancelableResponse {
    export enum NonCancellationReasonEnum {
        GkmmGrabKitchenMixMatchOrdersCannotBeCancelled = <any> 'GKMM (Grab Kitchen Mix & Match) orders cannot be cancelled',
        SelfPickUpOrdersCannotBeCancelled = <any> 'Self pick-up orders cannot be cancelled',
        ScheduledOrdersCannotBeCancelled = <any> 'Scheduled orders cannot be cancelled',
        DailyCancellationLimitReached = <any> 'Daily cancellation limit reached',
        WeeklyCancellationLimitReached = <any> 'Weekly cancellation limit reached',
        MonthlyCancellationLimitReached = <any> 'Monthly cancellation limit reached',
        DriverHasBeenAllocatedForTooLong = <any> 'Driver has been allocated for too long',
        DriverAppVersionIsOutdatedPreventingCancellation = <any> 'Driver App version is outdated preventing cancellation',
        OrderHasNotYetBeenAllocatedPreventingCancellation = <any> 'Order has not yet been allocated preventing cancellation',
        TheCurrentStatusOfTheOrderDoesNotAllowCancellation = <any> 'The current status of the order does not allow cancellation',
        DefaultError = <any> 'Default Error',
        Empty = <any> '',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
