// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from "./models";

/**
 * A JSON object containing code, symbol, and exponent for a given currency. Refer to [Country and Currency](#section/Getting-started/Country-and-currency).
 */
export class Currency {
  /**
   * The three-letter ISO currency code. This is the currency that is associated with the payment amount.
   */
  "code": Currency.CodeEnum;
  /**
   * The currency symbol.
   */
  "symbol": Currency.SymbolEnum;
  /**
   * The log base 10 of the number of times we have to multiply the major unit to get the minor unit. Should be 0 for VN and 2 for other countries (`SG`/`MY`/`ID`/`TH`/`PH`/`KH`/`MM`).
   */
  "exponent": number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{ name: string; baseName: string; type: string }> = [
    {
      name: "code",
      baseName: "code",
      type: "Currency.CodeEnum",
    },
    {
      name: "symbol",
      baseName: "symbol",
      type: "Currency.SymbolEnum",
    },
    {
      name: "exponent",
      baseName: "exponent",
      type: "number",
    },
  ];

  static getAttributeTypeMap() {
    return Currency.attributeTypeMap;
  }
}

export namespace Currency {
  export enum CodeEnum {
    Idr = <any>"IDR",
    Myr = <any>"MYR",
    Php = <any>"PHP",
    Sgd = <any>"SGD",
    Thb = <any>"THB",
    Vnd = <any>"VND",
    Khr = <any>"KHR",
    Mmk = <any>"MMK",
    UnknownDefaultOpenApi = <any>"11184809",
  }
  export enum SymbolEnum {
    Rp = <any>"Rp",
    Rm = <any>"RM",
    "₱" = <any>"₱",
    "S$" = <any>"S$",
    "฿" = <any>"฿",
    "₫" = <any>"₫",
    "៛" = <any>"៛",
    K = <any>"K",
    UnknownDefaultOpenApi = <any>"11184809",
  }
}
