// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* A JSON object containing order at table information. Only applicable for dine-in order. `null` if not applicable. Not present in [ListOrder](#tag/list-order/operation/list-orders) response.
*/
export class DineIn {
    /**
    * Table number.
    */
    'tableID'?: string;
    /**
    * The number of eaters.
    */
    'eaterCount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tableID",
            "baseName": "tableID",
            "type": "string"
        },
        {
            "name": "eaterCount",
            "baseName": "eaterCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DineIn.attributeTypeMap;
    }
}

