// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EditOrderItem {
    /**
    * The item\'s ID in Grab system that can be obtained from the [Submit Order Webhook](#tag/submit-order-webhook/operation/submit-order-webhook) request payload parameters under `items[].grabItemID`, or `items[].outOfStockInstruction.replacementGrabItemID` for item replacement. External item ID from Partner system is only supported when `ADDED` status and `isExternalItemID: true`.
    */
    'itemID': string;
    /**
    * The item\'s edited status. Leave empty string if there is no change to the item.
    */
    'status': EditOrderItem.StatusEnum;
    /**
    * The item\'s quantity. If the item is not being updated or deleted, use the original quantity.
    */
    'quantity'?: number;
    /**
    * Only applicable for `ADDED`status. Indicate if the `itemID` is an external item ID. Grab checks for the items that are mapped to the provided item ID, considering their availability. If multiple Grab items are found to be mapped to the provided external item ID, the last updated item will be chosen. If no suitable record is found, an 400 error will be returned to the partner, indicating that the submitted external item ID cannot be edited.
    */
    'isExternalItemID'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "itemID",
            "baseName": "itemID",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "EditOrderItem.StatusEnum"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "isExternalItemID",
            "baseName": "isExternalItemID",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EditOrderItem.attributeTypeMap;
    }
}

export namespace EditOrderItem {
    export enum StatusEnum {
        Deleted = <any> 'DELETED',
        Updated = <any> 'UPDATED',
        Added = <any> 'ADDED',
        Empty = <any> '',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
