// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EditOrderItem } from './editOrderItem';

/**
* Information about editing an existing order on GrabFood. 
*/
export class EditOrderRequest {
    /**
    * The order\'s ID that is returned from GrabFood. Refer to FAQs for more details about [orderID and shortOrderNumber](#section/Order/What\'s-the-difference-between-orderID-and-shortOrderNumber).
    */
    'orderID': string;
    /**
    * Specify the array of all items in the order, including deleted, added, updated and unchanged items.
    */
    'items': Array<EditOrderItem>;
    /**
    * This parameter specifies whether to recalculate the edited order without submitting it. It is intended for testing purposes only. This parameter is set to false by default, which means the edited order will be recalculated and re-submitted to partners. 
    */
    'onlyRecalculate'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderID",
            "baseName": "orderID",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<EditOrderItem>"
        },
        {
            "name": "onlyRecalculate",
            "baseName": "onlyRecalculate",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EditOrderRequest.attributeTypeMap;
    }
}

