// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Currency } from './currency';
import { MenuSection } from './menuSection';

/**
* 
*/
export class GetMenuOldResponse {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * The merchant\'s ID that is on the partner\'s database.
    */
    'partnerMerchantID'?: string;
    'currency': Currency;
    /**
    * An array of section JSON objects. Max 7 allowed. Refer to [Sections](#sections) for more information.
    */
    'sections': Array<MenuSection>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "partnerMerchantID",
            "baseName": "partnerMerchantID",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency"
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<MenuSection>"
        }    ];

    static getAttributeTypeMap() {
        return GetMenuOldResponse.attributeTypeMap;
    }
}

