// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetMembershipNativeResponsePointInfo } from './getMembershipNativeResponsePointInfo';

/**
* This response returns membership detail. 
*/
export class GetMembershipNativeResponse {
    /**
    * Status of the memberID.
    */
    'membershipStatus'?: GetMembershipNativeResponse.MembershipStatusEnum;
    'pointInfo'?: GetMembershipNativeResponsePointInfo;
    /**
    * Earliest points expiry date. In `yyyy-mm-dd` format
    */
    'pointsExpireDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "membershipStatus",
            "baseName": "membershipStatus",
            "type": "GetMembershipNativeResponse.MembershipStatusEnum"
        },
        {
            "name": "pointInfo",
            "baseName": "pointInfo",
            "type": "GetMembershipNativeResponsePointInfo"
        },
        {
            "name": "pointsExpireDate",
            "baseName": "pointsExpireDate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetMembershipNativeResponse.attributeTypeMap;
    }
}

export namespace GetMembershipNativeResponse {
    export enum MembershipStatusEnum {
        Valid = <any> 'VALID',
        Invalid = <any> 'INVALID',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
