// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Currency } from './currency';
import { MenuCategory } from './menuCategory';
import { SellingTime } from './sellingTime';

/**
* 
*/
export class GetMenuNewResponse {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * The merchant\'s ID that is on the partner\'s database.
    */
    'partnerMerchantID'?: string;
    'currency': Currency;
    /**
    * An array of sellingTimes JSON objects. Max 20 allowed. Refer to [Selling Times](#selling-times) for more information.
    */
    'sellingTimes': Array<SellingTime>;
    /**
    * An array of category JSON objects. Max 100 allowed. Refer to [Categories](#categories) for more information.
    */
    'categories': Array<MenuCategory>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "partnerMerchantID",
            "baseName": "partnerMerchantID",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "Currency"
        },
        {
            "name": "sellingTimes",
            "baseName": "sellingTimes",
            "type": "Array<SellingTime>"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<MenuCategory>"
        }    ];

    static getAttributeTypeMap() {
        return GetMenuNewResponse.attributeTypeMap;
    }
}

