// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RewardItem } from './rewardItem';

/**
* This request submits membership detail and order value to get reward calculation. 
*/
export class GetRewardNativeRequest {
    /**
    * The unique member ID on the partner\'s database.
    */
    'memberID'?: string;
    /**
    * Grab merchant\'s ID.
    */
    'merchantID'?: string;
    'items'?: Array<RewardItem>;
    /**
    * The post-discount order value.
    */
    'orderValue'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "memberID",
            "baseName": "memberID",
            "type": "string"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<RewardItem>"
        },
        {
            "name": "orderValue",
            "baseName": "orderValue",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetRewardNativeRequest.attributeTypeMap;
    }
}

