// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Order } from './order';

/**
* 
*/
export class ListOrdersResponse {
    /**
    * The boolean value to indicate if there is more order data. If `true`, you can continue requesting with page+1.
    */
    'more'?: boolean;
    'orders'?: Array<Order>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "more",
            "baseName": "more",
            "type": "boolean"
        },
        {
            "name": "orders",
            "baseName": "orders",
            "type": "Array<Order>"
        }    ];

    static getAttributeTypeMap() {
        return ListOrdersResponse.attributeTypeMap;
    }
}

