// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This request marks an order as ready for delivery or completed on GrabFood. 
*/
export class MarkOrderRequest {
    /**
    * The order\'s ID that is returned from GrabFood. Refer to FAQs for more details about [orderID and shortOrderNumber](#section/Order/What\'s-the-difference-between-orderID-and-shortOrderNumber).
    */
    'orderID': string;
    /**
    * The status to be marked accordingly.  * `1` - mark order as ready  * `2` - mark order as completed and only applicable to **dine-in** orders 
    */
    'markStatus': MarkOrderRequest.MarkStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderID",
            "baseName": "orderID",
            "type": "string"
        },
        {
            "name": "markStatus",
            "baseName": "markStatus",
            "type": "MarkOrderRequest.MarkStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return MarkOrderRequest.attributeTypeMap;
    }
}

export namespace MarkOrderRequest {
    export enum MarkStatusEnum {
        NUMBER_1 = <any> 1,
        NUMBER_2 = <any> 2,
        NUMBER_unknown_default_open_api = <any> 11184809
    }
}
