// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuSectionCategory } from './menuSectionCategory';
import { ServiceHours } from './serviceHours';

export class MenuSection {
    /**
    * The section\'s ID in the partner system. 
    */
    'id': string;
    /**
    * The name of the section.
    */
    'name': string;
    'serviceHours': ServiceHours;
    /**
    * An array of category JSON objects. Max 100 allowed per section. Refer to [Categories](#categories) for more information.
    */
    'categories': Array<MenuSectionCategory>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "serviceHours",
            "baseName": "serviceHours",
            "type": "ServiceHours"
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<MenuSectionCategory>"
        }    ];

    static getAttributeTypeMap() {
        return MenuSection.attributeTypeMap;
    }
}

