// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This request pushes the state of a menu sync operation. 
*/
export class MenuSyncWebhookRequest {
    /**
    * An universally unique identifier (UUID) string. Used to uniquely identify a webhook request. Partners should use this value to distinguish between different webhook requests. If two requests contain the same requestID, only the first request should be considered and later requests **must** be ignored or discarded. 
    */
    'requestID'?: string;
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * The merchant\'s ID that is on the partner\'s database.
    */
    'partnerMerchantID'?: string;
    /**
    * An UUID string. Uniquely identifies a menu sync job. This can be found from the [Menu Update Notification](#tag/update-menu-noti) API response header. 
    */
    'jobID'?: string;
    /**
    * Indicates the time of menu sync status change. This is based on ISO_8601/RFC3339. For example: `2022-07-29T15:55:59Z`. 
    */
    'updatedAt'?: string;
    /**
    * Indicates the state of the menu sync job.
    */
    'status'?: MenuSyncWebhookRequest.StatusEnum;
    /**
    * A string array of errors that occurred during processing. This array is empty if the status is not `FAILED`.
    */
    'errors'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestID",
            "baseName": "requestID",
            "type": "string"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "partnerMerchantID",
            "baseName": "partnerMerchantID",
            "type": "string"
        },
        {
            "name": "jobID",
            "baseName": "jobID",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "MenuSyncWebhookRequest.StatusEnum"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return MenuSyncWebhookRequest.attributeTypeMap;
    }
}

export namespace MenuSyncWebhookRequest {
    export enum StatusEnum {
        Queueing = <any> 'QUEUEING',
        Processing = <any> 'PROCESSING',
        Success = <any> 'SUCCESS',
        Failed = <any> 'FAILED',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
