// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuSyncFailModifier } from './menuSyncFailModifier';

export class MenuSyncFailModifierGroup {
    'id'?: string;
    /**
    * An array of strings of error message.
    */
    'errors'?: Array<string>;
    'modifiers'?: Array<MenuSyncFailModifier>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>"
        },
        {
            "name": "modifiers",
            "baseName": "modifiers",
            "type": "Array<MenuSyncFailModifier>"
        }    ];

    static getAttributeTypeMap() {
        return MenuSyncFailModifierGroup.attributeTypeMap;
    }
}

