// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuSectionCategoryItem } from './menuSectionCategoryItem';

export class MenuSectionCategory {
    /**
    * The category\'s ID that is on the partner system. This ID should be unique with a min length of 1 and max of 64.
    */
    'id': string;
    /**
    * The name of the category.
    */
    'name': string;
    /**
    * Translation of the category name. Only support up to 1 translated language. Refer [Menu Translation](#section/Menu-Translation).
    */
    'nameTranslation'?: { [key: string]: string; };
    /**
    * The status for the category. Refer to FAQs for more details about [availableStatus](#section/Menu/What-is-availableStatus).
    */
    'availableStatus': MenuSectionCategory.AvailableStatusEnum;
    /**
    * An array of item JSON objects. Max 300 allowed per category. Refer to [Items](#items) for more information.
    */
    'items': Array<MenuSectionCategoryItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nameTranslation",
            "baseName": "nameTranslation",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "availableStatus",
            "baseName": "availableStatus",
            "type": "MenuSectionCategory.AvailableStatusEnum"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<MenuSectionCategoryItem>"
        }    ];

    static getAttributeTypeMap() {
        return MenuSectionCategory.attributeTypeMap;
    }
}

export namespace MenuSectionCategory {
    export enum AvailableStatusEnum {
        Available = <any> 'AVAILABLE',
        Unavailable = <any> 'UNAVAILABLE',
        Hide = <any> 'HIDE',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
