// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuSyncFailItem } from './menuSyncFailItem';

export class MenuSyncFailCategory {
    /**
    * The category\'s ID that is on the partner system. This ID should be unique with a min length of 1 and max of 64.
    */
    'id'?: string;
    /**
    * An array of strings of error message.
    */
    'errors'?: Array<string>;
    /**
    * An array of item JSON objects. Max 300 allowed per category. Refer to [Items](#items) for more information.
    */
    'items'?: Array<MenuSyncFailItem>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<MenuSyncFailItem>"
        }    ];

    static getAttributeTypeMap() {
        return MenuSyncFailCategory.attributeTypeMap;
    }
}

