// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AdvancedPricing } from './advancedPricing';

export class MenuModifier {
    /**
    * The modifier\'s ID that is on the partner\'s system. This ID should be unique.
    */
    'id': string;
    /**
    * The name of the modifier.
    */
    'name': string;
    /**
    * Translation of the modifier name. Only support up to 1 translated language. Refer [Menu Translation](#section/Menu-Translation).
    */
    'nameTranslation'?: { [key: string]: string; };
    /**
    * The status for the modifier. Refer to FAQs for more details about [availableStatus](#section/Menu/What-is-availableStatus).
    */
    'availableStatus': MenuModifier.AvailableStatusEnum;
    /**
    * The modifier\'s price in minor format. Refer to FAQs for more details about [tax](#section/Menu/Is-the-menu-price-with-or-without-tax).
    */
    'price'?: number;
    /**
    * The barcode Number (GTIN). GTIN must be 8, 12, 13, 14 numeric digits.
    */
    'barcode'?: string;
    /**
    * The sort or display order of the modifier within the menu.
    */
    'sequence'?: number;
    'advancedPricing'?: AdvancedPricing;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nameTranslation",
            "baseName": "nameTranslation",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "availableStatus",
            "baseName": "availableStatus",
            "type": "MenuModifier.AvailableStatusEnum"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "barcode",
            "baseName": "barcode",
            "type": "string"
        },
        {
            "name": "sequence",
            "baseName": "sequence",
            "type": "number"
        },
        {
            "name": "advancedPricing",
            "baseName": "advancedPricing",
            "type": "AdvancedPricing"
        }    ];

    static getAttributeTypeMap() {
        return MenuModifier.attributeTypeMap;
    }
}

export namespace MenuModifier {
    export enum AvailableStatusEnum {
        Available = <any> 'AVAILABLE',
        Unavailable = <any> 'UNAVAILABLE',
        Unavailabletoday = <any> 'UNAVAILABLETODAY',
        Hide = <any> 'HIDE',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
