// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MenuSyncFail } from './menuSyncFail';

/**
* 
*/
export class MenuSyncResponse {
    /**
    * The Unix time the specified menu was created in GrabFood\'s database.
    */
    'createdTime': Date;
    /**
    * The Unix time the specified menu was created in GrabFood\'s database.
    */
    'updatedTime': Date;
    /**
    * The status code for this request. See [Menu sync response statuses](#section/Menu-sync-response-statuses) for more information.
    */
    'code': MenuSyncResponse.CodeEnum;
    /**
    * An array of strings of error message.
    */
    'errors'?: Array<string> | null;
    'sections'?: Array<MenuSyncFail> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createdTime",
            "baseName": "createdTime",
            "type": "Date"
        },
        {
            "name": "updatedTime",
            "baseName": "updatedTime",
            "type": "Date"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "MenuSyncResponse.CodeEnum"
        },
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<string>"
        },
        {
            "name": "sections",
            "baseName": "sections",
            "type": "Array<MenuSyncFail>"
        }    ];

    static getAttributeTypeMap() {
        return MenuSyncResponse.attributeTypeMap;
    }
}

export namespace MenuSyncResponse {
    export enum CodeEnum {
        Success = <any> 'Success',
        PartialSuccess = <any> 'PartialSuccess',
        InQueuing = <any> 'InQueuing',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
