// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This request submits membership registration request to partner. 
*/
export class NotifyMembershipWebviewRequest {
    /**
    * The unique member ID on the partner\'s database.
    */
    'memberID'?: string;
    /**
    * The id used to identify an unique grab user.
    */
    'grabID'?: string;
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * Action completed in partner\'s webview.
    */
    'action'?: NotifyMembershipWebviewRequest.ActionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "memberID",
            "baseName": "memberID",
            "type": "string"
        },
        {
            "name": "grabID",
            "baseName": "grabID",
            "type": "string"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "NotifyMembershipWebviewRequest.ActionEnum"
        }    ];

    static getAttributeTypeMap() {
        return NotifyMembershipWebviewRequest.attributeTypeMap;
    }
}

export namespace NotifyMembershipWebviewRequest {
    export enum ActionEnum {
        Link = <any> 'LINK',
        Register = <any> 'REGISTER',
        Unlink = <any> 'UNLINK',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
