// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This request marks an order as delivered on GrabFood. 
*/
export class OrderDeliveryRequest {
    /**
    * The order\'s ID that is returned from GrabFood. Refer to FAQs for more details about [orderID and shortOrderNumber](#section/Order/What\'s-the-difference-between-orderID-and-shortOrderNumber).
    */
    'orderID': string;
    /**
    * Specify the order\'s initial state.
    */
    'fromState': OrderDeliveryRequest.FromStateEnum;
    /**
    * Specify the order\'s new state.
    */
    'toState': OrderDeliveryRequest.ToStateEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderID",
            "baseName": "orderID",
            "type": "string"
        },
        {
            "name": "fromState",
            "baseName": "fromState",
            "type": "OrderDeliveryRequest.FromStateEnum"
        },
        {
            "name": "toState",
            "baseName": "toState",
            "type": "OrderDeliveryRequest.ToStateEnum"
        }    ];

    static getAttributeTypeMap() {
        return OrderDeliveryRequest.attributeTypeMap;
    }
}

export namespace OrderDeliveryRequest {
    export enum FromStateEnum {
        Accepted = <any> 'Accepted',
        FindDriver = <any> 'FindDriver',
        Collected = <any> 'Collected',
        UnknownDefaultOpenApi = <any> '11184809'
    }
    export enum ToStateEnum {
        FindDriver = <any> 'FindDriver',
        Collected = <any> 'Collected',
        Delivered = <any> 'Delivered',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
