// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrderItemModifier } from './orderItemModifier';
import { OutOfStockInstruction } from './outOfStockInstruction';

export class OrderItem {
    /**
    * The item\'s externalID in the partner system. 
    */
    'id': string;
    /**
    * The item\'s ID in Grab system. Partner can use this field in the `EditOrder` endpoint.
    */
    'grabItemID': string;
    /**
    * The number of the item ordered.
    */
    'quantity': number;
    /**
    * The price for a single item along with its associated modifiers in minor unit and tax-inclusive.  ``` price = Item price(tax inclusive) + Modifier price(tax inclusive) | (2241*1.06)+(165*1.06)=2550 
    */
    'price': number;
    /**
    * Tax in minor format for a single item along with its associated modifiers. `0` if tax configuration is absent. Refer to FAQs for more details about [tax](#section/Order/How-is-tax-calculated). ``` tax = Item tax + Modifier tax | (2241*0.06)+(165*0.06)=144 
    */
    'tax'?: number;
    /**
    * An extra note for the merchant. Empty if no note from consumer. 
    */
    'specifications'?: string;
    'outOfStockInstruction'?: OutOfStockInstruction | null;
    /**
    * An array of JSON objects modifiers.
    */
    'modifiers'?: Array<OrderItemModifier>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "grabItemID",
            "baseName": "grabItemID",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number"
        },
        {
            "name": "specifications",
            "baseName": "specifications",
            "type": "string"
        },
        {
            "name": "outOfStockInstruction",
            "baseName": "outOfStockInstruction",
            "type": "OutOfStockInstruction"
        },
        {
            "name": "modifiers",
            "baseName": "modifiers",
            "type": "Array<OrderItemModifier>"
        }    ];

    static getAttributeTypeMap() {
        return OrderItem.attributeTypeMap;
    }
}

