// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrderPromo {
    /**
    * Promo code applied in the order.
    */
    'code'?: string;
    /**
    * Promo description.
    */
    'description'?: string;
    /**
    * Name of the promotion.
    */
    'name'?: string;
    /**
    * Promo amount applied in the order, in local currency. This amount is rounded into whole number.
    */
    'promoAmount'?: number;
    /**
    * The merchant\'s funded ratio of the promo in percentage.
    */
    'mexFundedRatio'?: number;
    /**
    * The merchant\'s promo fund in the minor unit. Calculated based on merchant funded ratio.
    */
    'mexFundedAmount'?: number;
    /**
    * The subtotal of the order basket in minor unit.
    */
    'targetedPrice'?: number;
    /**
    * Promo amount applied in the order in minor unit.
    */
    'promoAmountInMin'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "promoAmount",
            "baseName": "promoAmount",
            "type": "number"
        },
        {
            "name": "mexFundedRatio",
            "baseName": "mexFundedRatio",
            "type": "number"
        },
        {
            "name": "mexFundedAmount",
            "baseName": "mexFundedAmount",
            "type": "number"
        },
        {
            "name": "targetedPrice",
            "baseName": "targetedPrice",
            "type": "number"
        },
        {
            "name": "promoAmountInMin",
            "baseName": "promoAmountInMin",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OrderPromo.attributeTypeMap;
    }
}

