// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OrderFreeItem } from './orderFreeItem';

export class OrderCampaign {
    /**
    * The campaign\'s ID returned by GrabFood upon campaign creation.
    */
    'id'?: string;
    /**
    * The name of the campaign. This campaign name has been automatically generated by Grab for display in the customer app.
    */
    'name'?: string;
    /**
    * The campaign name provided by the merchant in [Create Campaign](#tag/create-campaign). Whitelist required, reach out to your integration manager.
    */
    'campaignNameForMex'?: string;
    /**
    * The campaign level.
    */
    'level'?: OrderCampaign.LevelEnum;
    /**
    * The type of campaign.
    */
    'type'?: OrderCampaign.TypeEnum;
    /**
    * The redemption count of same campaign in this order.
    */
    'usageCount'?: number;
    /**
    * The ratio funded by the merchant in percentage.
    */
    'mexFundedRatio'?: number;
    /**
    * The total discount amount in minor unit format applied to the order based on the campaign\'s usage count. The amount is rounded to the nearest value for `VND`, `IDR`, and `THB`, as decimals are not supported.  ``` deductedAmount = Item price(tax inclusive) * 20% discount | 2375*0.2=475 
    */
    'deductedAmount'?: number;
    /**
    * The part that the campaign is applied.
    */
    'deductedPart'?: OrderCampaign.DeductedPartEnum;
    /**
    * An array of item IDs that get discount under this campaign. `null` if no item applied in this campaign.
    */
    'appliedItemIDs'?: Array<string> | null;
    'freeItem'?: OrderFreeItem;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "campaignNameForMex",
            "baseName": "campaignNameForMex",
            "type": "string"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "OrderCampaign.LevelEnum"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "OrderCampaign.TypeEnum"
        },
        {
            "name": "usageCount",
            "baseName": "usageCount",
            "type": "number"
        },
        {
            "name": "mexFundedRatio",
            "baseName": "mexFundedRatio",
            "type": "number"
        },
        {
            "name": "deductedAmount",
            "baseName": "deductedAmount",
            "type": "number"
        },
        {
            "name": "deductedPart",
            "baseName": "deductedPart",
            "type": "OrderCampaign.DeductedPartEnum"
        },
        {
            "name": "appliedItemIDs",
            "baseName": "appliedItemIDs",
            "type": "Array<string>"
        },
        {
            "name": "freeItem",
            "baseName": "freeItem",
            "type": "OrderFreeItem"
        }    ];

    static getAttributeTypeMap() {
        return OrderCampaign.attributeTypeMap;
    }
}

export namespace OrderCampaign {
    export enum LevelEnum {
        Item = <any> 'item',
        Category = <any> 'category',
        Order = <any> 'order',
        DeliveryFee = <any> 'delivery_fee',
        Bundle = <any> 'bundle',
        UnknownDefaultOpenApi = <any> '11184809'
    }
    export enum TypeEnum {
        Percentage = <any> 'percentage',
        Net = <any> 'net',
        Delivery = <any> 'delivery',
        FreeItem = <any> 'freeItem',
        BundleSameNet = <any> 'bundleSameNet',
        BundleSamePercentage = <any> 'bundleSamePercentage',
        BundleSameFixPrice = <any> 'bundleSameFixPrice',
        UnknownDefaultOpenApi = <any> '11184809'
    }
    export enum DeductedPartEnum {
        BasketAmount = <any> 'basket_amount',
        DeliveryFee = <any> 'delivery_fee',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
