// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OrderItemModifier {
    /**
    * The modifier\'s ID that is on the partner\'s system.
    */
    'id'?: string;
    /**
    * The modifier\'s price (tax-inclusive) in minor format.  ``` price = round(165 * (1 + 0.06)) = 175 
    */
    'price'?: number;
    /**
    * Tax in minor format for 1 modifier. Refer to FAQs for more details about [tax](#section/Order/How-is-tax-calculated). ``` tax = 165*0.06=10 
    */
    'tax'?: number;
    /**
    * The number of modifiers present. The value is always 1.
    */
    'quantity'?: OrderItemModifier.QuantityEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "tax",
            "baseName": "tax",
            "type": "number"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "OrderItemModifier.QuantityEnum"
        }    ];

    static getAttributeTypeMap() {
        return OrderItemModifier.attributeTypeMap;
    }
}

export namespace OrderItemModifier {
    export enum QuantityEnum {
        NUMBER_1 = <any> 1,
        NUMBER_unknown_default_open_api = <any> 11184809
    }
}
