// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* The featureFlag JSON object containing an order\'s feature related information.
*/
export class OrderFeatureFlags {
    /**
    * The acceptance type for the order. Refer to FAQs for more details about [orderAcceptedType](#section/Order/How-do-I-identify-if-a-particular-order-is-auto-or-manual-acceptance). 
    */
    'orderAcceptedType': OrderFeatureFlags.OrderAcceptedTypeEnum;
    /**
    * The type of order. 
    */
    'orderType': OrderFeatureFlags.OrderTypeEnum;
    /**
    * A boolean value that indicates if the order is edited. 
    */
    'isMexEditOrder'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderAcceptedType",
            "baseName": "orderAcceptedType",
            "type": "OrderFeatureFlags.OrderAcceptedTypeEnum"
        },
        {
            "name": "orderType",
            "baseName": "orderType",
            "type": "OrderFeatureFlags.OrderTypeEnum"
        },
        {
            "name": "isMexEditOrder",
            "baseName": "isMexEditOrder",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return OrderFeatureFlags.attributeTypeMap;
    }
}

export namespace OrderFeatureFlags {
    export enum OrderAcceptedTypeEnum {
        Auto = <any> 'AUTO',
        Manual = <any> 'MANUAL',
        UnknownDefaultOpenApi = <any> '11184809'
    }
    export enum OrderTypeEnum {
        TakeAway = <any> 'TakeAway',
        DeliveredByGrab = <any> 'DeliveredByGrab',
        DeliveredByRestaurant = <any> 'DeliveredByRestaurant',
        DineIn = <any> 'DineIn',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
