// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Information related to the order ready time estimation.
*/
export class OrderReadyEstimation {
    /**
    * A boolean value indicating if the order ready time can be changed.
    */
    'allowChange': boolean;
    /**
    * The order ready time for this order estimated by GrabFood, based on ISO_8601/RFC3339.
    */
    'estimatedOrderReadyTime': Date;
    /**
    * The max allowed order ready time for this order, based on ISO_8601/RFC3339.
    */
    'maxOrderReadyTime': Date;
    /**
    * The new order ready time for this order. Only present after a new order ready time is set (default will be null), based on ISO_8601/RFC3339.
    */
    'newOrderReadyTime'?: Date | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "allowChange",
            "baseName": "allowChange",
            "type": "boolean"
        },
        {
            "name": "estimatedOrderReadyTime",
            "baseName": "estimatedOrderReadyTime",
            "type": "Date"
        },
        {
            "name": "maxOrderReadyTime",
            "baseName": "maxOrderReadyTime",
            "type": "Date"
        },
        {
            "name": "newOrderReadyTime",
            "baseName": "newOrderReadyTime",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return OrderReadyEstimation.attributeTypeMap;
    }
}

