// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Free item information for `freeItem` campaign.
*/
export class OrderFreeItem {
    /**
    * The free item\'s externalID in the partner system. Empty if not applicable.
    */
    'id'?: string;
    /**
    * The name of the free item. Empty if not applicable. 
    */
    'name'?: string;
    /**
    * The item\'s quantity. Maximum is **1**.
    */
    'quantity'?: number;
    /**
    * The item\'s price in minor unit format.
    */
    'price'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OrderFreeItem.attributeTypeMap;
    }
}

