// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An JSON object that indicates the instructions to be taken by the merchant when the item is out of stock.
*/
export class OutOfStockInstruction {
    /**
    * The short instruction message.
    */
    'title'?: string;
    /**
    * Type of out-of-stock instruction chosen by customer. `CONTACT` is disabled by default, kindly reach out to your integration manager if you wish to receive this instruction.
    */
    'instructionType'?: OutOfStockInstruction.InstructionTypeEnum;
    /**
    * The preferred item\'s ID in the partner system. Only applicable when the instructionType is `SPECIFIC_ITEM`.
    */
    'replacementItemID'?: string;
    /**
    * The preferred item\'s ID in the Grab system. Only applicable when the instructionType is `SPECIFIC_ITEM`.
    */
    'replacementGrabItemID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "instructionType",
            "baseName": "instructionType",
            "type": "OutOfStockInstruction.InstructionTypeEnum"
        },
        {
            "name": "replacementItemID",
            "baseName": "replacementItemID",
            "type": "string"
        },
        {
            "name": "replacementGrabItemID",
            "baseName": "replacementGrabItemID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return OutOfStockInstruction.attributeTypeMap;
    }
}

export namespace OutOfStockInstruction {
    export enum InstructionTypeEnum {
        Remove = <any> 'REMOVE',
        Cancel = <any> 'CANCEL',
        SpecificItem = <any> 'SPECIFIC_ITEM',
        Contact = <any> 'CONTACT',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
