// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PartnerOauthResponse {
    /**
    * The OAuth 2.0 access token issued by the partner.
    */
    'access_token'?: string;
    /**
    * The type of token issued which is case insensitive.
    */
    'token_type'?: PartnerOauthResponse.TokenTypeEnum;
    /**
    * The access token lifespan in seconds.
    */
    'expires_in'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "access_token",
            "baseName": "access_token",
            "type": "string"
        },
        {
            "name": "token_type",
            "baseName": "token_type",
            "type": "PartnerOauthResponse.TokenTypeEnum"
        },
        {
            "name": "expires_in",
            "baseName": "expires_in",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PartnerOauthResponse.attributeTypeMap;
    }
}

export namespace PartnerOauthResponse {
    export enum TokenTypeEnum {
        Bearer = <any> 'Bearer',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
