// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Purchasability is set to true by default for all service type, unless it is explicitly set to false. Modifier will reuse it’s item’s purchasability. Refer [Service Based Menu](#section/Service-Based-Menu). 
*/
export class Purchasability {
    'Delivery_OnDemand_GrabApp'?: boolean;
    'Delivery_Scheduled_GrabApp'?: boolean;
    'SelfPickUp_OnDemand_GrabApp'?: boolean;
    'DineIn_OnDemand_GrabApp'?: boolean;
    'Delivery_OnDemand_StoreFront'?: boolean;
    'Delivery_Scheduled_StoreFront'?: boolean;
    'SelfPickUp_OnDemand_StoreFront'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "Delivery_OnDemand_GrabApp",
            "baseName": "Delivery_OnDemand_GrabApp",
            "type": "boolean"
        },
        {
            "name": "Delivery_Scheduled_GrabApp",
            "baseName": "Delivery_Scheduled_GrabApp",
            "type": "boolean"
        },
        {
            "name": "SelfPickUp_OnDemand_GrabApp",
            "baseName": "SelfPickUp_OnDemand_GrabApp",
            "type": "boolean"
        },
        {
            "name": "DineIn_OnDemand_GrabApp",
            "baseName": "DineIn_OnDemand_GrabApp",
            "type": "boolean"
        },
        {
            "name": "Delivery_OnDemand_StoreFront",
            "baseName": "Delivery_OnDemand_StoreFront",
            "type": "boolean"
        },
        {
            "name": "Delivery_Scheduled_StoreFront",
            "baseName": "Delivery_Scheduled_StoreFront",
            "type": "boolean"
        },
        {
            "name": "SelfPickUp_OnDemand_StoreFront",
            "baseName": "SelfPickUp_OnDemand_StoreFront",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return Purchasability.attributeTypeMap;
    }
}

