// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 
*/
export class PushIntegrationStatusWebhookRequest {
    /**
    * The merchant\'s ID that is on the partner\'s database.
    */
    'partnerMerchantID': string;
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'grabMerchantID': string;
    /**
    * The store integration status. - `INACTIVE`: Merchant integration deactivated - `ACTIVE`: Merchant integration activated - `SYNCING`: Merchant integration is syncing - `FAILED`: Merchant integration has failed 
    */
    'integrationStatus': PushIntegrationStatusWebhookRequest.IntegrationStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "partnerMerchantID",
            "baseName": "partnerMerchantID",
            "type": "string"
        },
        {
            "name": "grabMerchantID",
            "baseName": "grabMerchantID",
            "type": "string"
        },
        {
            "name": "integrationStatus",
            "baseName": "integrationStatus",
            "type": "PushIntegrationStatusWebhookRequest.IntegrationStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return PushIntegrationStatusWebhookRequest.attributeTypeMap;
    }
}

export namespace PushIntegrationStatusWebhookRequest {
    export enum IntegrationStatusEnum {
        Inactive = <any> 'INACTIVE',
        Active = <any> 'ACTIVE',
        Syncing = <any> 'SYNCING',
        Failed = <any> 'FAILED',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
