// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RedeemResult } from './redeemResult';
import { Voucher } from './voucher';

/**
* 
*/
export class RedeemDineInVoucherResponse {
    /**
    * This certificateID is decoded from scanning the QR code, and 1:1 mapping with `voucherCode`.
    */
    'certificateID'?: string;
    /**
    * A short code for the dine-in voucher purchased by the user.
    */
    'voucherCode'?: string;
    'voucher'?: Voucher;
    'redeemResult'?: RedeemResult;
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * The dine-in voucher campaign\'s ID in GrabFood\'s database.
    */
    'campaignID'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "certificateID",
            "baseName": "certificateID",
            "type": "string"
        },
        {
            "name": "voucherCode",
            "baseName": "voucherCode",
            "type": "string"
        },
        {
            "name": "voucher",
            "baseName": "voucher",
            "type": "Voucher"
        },
        {
            "name": "redeemResult",
            "baseName": "redeemResult",
            "type": "RedeemResult"
        },
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "campaignID",
            "baseName": "campaignID",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RedeemDineInVoucherResponse.attributeTypeMap;
    }
}

