// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ServiceHours } from './serviceHours';

export class SellingTime {
    /**
    * The selling time group start time in date & time format. UTC format is expected. 
    */
    'startTime'?: string;
    /**
    * The selling time group end time in date & time format. UTC format is expected. 
    */
    'endTime'?: string;
    /**
    * The selling time\'s ID on the partner system. This ID should be unique with length min 1 and max 64. 
    */
    'id'?: string;
    /**
    * The name of the selling time. 
    */
    'name'?: string;
    'serviceHours'?: ServiceHours;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "string"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "serviceHours",
            "baseName": "serviceHours",
            "type": "ServiceHours"
        }    ];

    static getAttributeTypeMap() {
        return SellingTime.attributeTypeMap;
    }
}

