// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ServiceHour } from './serviceHour';

/**
* A JSON object with serviceHours for each day of the week.
*/
export class ServiceHours {
    'mon': ServiceHour;
    'tue': ServiceHour;
    'wed': ServiceHour;
    'thu': ServiceHour;
    'fri': ServiceHour;
    'sat': ServiceHour;
    'sun': ServiceHour;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mon",
            "baseName": "mon",
            "type": "ServiceHour"
        },
        {
            "name": "tue",
            "baseName": "tue",
            "type": "ServiceHour"
        },
        {
            "name": "wed",
            "baseName": "wed",
            "type": "ServiceHour"
        },
        {
            "name": "thu",
            "baseName": "thu",
            "type": "ServiceHour"
        },
        {
            "name": "fri",
            "baseName": "fri",
            "type": "ServiceHour"
        },
        {
            "name": "sat",
            "baseName": "sat",
            "type": "ServiceHour"
        },
        {
            "name": "sun",
            "baseName": "sun",
            "type": "ServiceHour"
        }    ];

    static getAttributeTypeMap() {
        return ServiceHours.attributeTypeMap;
    }
}

