// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OpenPeriod } from './openPeriod';

/**
* A JSON object serviceHour for each day. An empty JSON object indicates the menu item is not available on the day.
*/
export class ServiceHour {
    /**
    * Defines the specific time period during which the menu is available  - OpenPeriod = open only in given periods - OpenAllDay = open 24 hours - CloseAllDay = closed 24 hours 
    */
    'openPeriodType': ServiceHour.OpenPeriodTypeEnum;
    /**
    * An array of open periods. Only required when `openPeriodType` is **OpenPeriod**
    */
    'periods'?: Array<OpenPeriod>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "openPeriodType",
            "baseName": "openPeriodType",
            "type": "ServiceHour.OpenPeriodTypeEnum"
        },
        {
            "name": "periods",
            "baseName": "periods",
            "type": "Array<OpenPeriod>"
        }    ];

    static getAttributeTypeMap() {
        return ServiceHour.attributeTypeMap;
    }
}

export namespace ServiceHour {
    export enum OpenPeriodTypeEnum {
        OpenPeriod = <any> 'OpenPeriod',
        OpenAllDay = <any> 'OpenAllDay',
        CloseAllDay = <any> 'CloseAllDay',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
