// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SpecialOpeningHourMetadata } from './specialOpeningHourMetadata';
import { SpecialOpeningHourOpeningHours } from './specialOpeningHourOpeningHours';

export class SpecialOpeningHour {
    /**
    * The start date of store special opening hours.
    */
    'startDate'?: string;
    /**
    * The end date of store special opening hours.
    */
    'endDate'?: string;
    'metadata'?: SpecialOpeningHourMetadata;
    'openingHours'?: SpecialOpeningHourOpeningHours;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string"
        },
        {
            "name": "endDate",
            "baseName": "endDate",
            "type": "string"
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "SpecialOpeningHourMetadata"
        },
        {
            "name": "openingHours",
            "baseName": "openingHours",
            "type": "SpecialOpeningHourOpeningHours"
        }    ];

    static getAttributeTypeMap() {
        return SpecialOpeningHour.attributeTypeMap;
    }
}

