// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OpenPeriod } from './openPeriod';

/**
* A JSON object that describes the store hour for each day.
*/
export class StoreHour {
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'mon': Array<OpenPeriod>;
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'tue': Array<OpenPeriod>;
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'wed': Array<OpenPeriod>;
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'thu': Array<OpenPeriod>;
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'fri': Array<OpenPeriod>;
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'sat': Array<OpenPeriod>;
    /**
    * An array of open periods. Maximum of 3 periods. Blank indicates store close.
    */
    'sun': Array<OpenPeriod>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mon",
            "baseName": "mon",
            "type": "Array<OpenPeriod>"
        },
        {
            "name": "tue",
            "baseName": "tue",
            "type": "Array<OpenPeriod>"
        },
        {
            "name": "wed",
            "baseName": "wed",
            "type": "Array<OpenPeriod>"
        },
        {
            "name": "thu",
            "baseName": "thu",
            "type": "Array<OpenPeriod>"
        },
        {
            "name": "fri",
            "baseName": "fri",
            "type": "Array<OpenPeriod>"
        },
        {
            "name": "sat",
            "baseName": "sat",
            "type": "Array<OpenPeriod>"
        },
        {
            "name": "sun",
            "baseName": "sun",
            "type": "Array<OpenPeriod>"
        }    ];

    static getAttributeTypeMap() {
        return StoreHour.attributeTypeMap;
    }
}

