// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object contains store status info
*/
export class StoreStatusResponse {
    /**
    * The code of store close reason. Blank indicates store is currently open.
    */
    'closeReason': StoreStatusResponse.CloseReasonEnum;
    /**
    * Indicate whether the store is in special opening hour range.
    */
    'isInSpecialOpeningHourRange': boolean;
    /**
    * Indicate whether the store is open.
    */
    'isOpen': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "closeReason",
            "baseName": "closeReason",
            "type": "StoreStatusResponse.CloseReasonEnum"
        },
        {
            "name": "isInSpecialOpeningHourRange",
            "baseName": "isInSpecialOpeningHourRange",
            "type": "boolean"
        },
        {
            "name": "isOpen",
            "baseName": "isOpen",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return StoreStatusResponse.attributeTypeMap;
    }
}

export namespace StoreStatusResponse {
    export enum CloseReasonEnum {
        MexPaused = <any> 'mex_paused',
        OpsPaused = <any> 'ops_paused',
        OutOfSpecialOpeningHours = <any> 'out_of_special_opening_hours',
        OutOfOpeningHours = <any> 'out_of_opening_hours',
        Inactive = <any> 'inactive',
        OpsPausedWithoutComm = <any> 'ops_paused_without_comm',
        Restricted = <any> 'restricted',
        Suspended = <any> 'suspended',
        ParseDataFail = <any> 'parse_data_fail',
        Empty = <any> '',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
