// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateAdvancedPricing } from './updateAdvancedPricing';
import { UpdatePurchasability } from './updatePurchasability';

/**
* Information about the GrabFood client updating their food menu. 
*/
export class UpdateMenuItem {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID': string;
    /**
    * The record type that you want to update.
    */
    'field': UpdateMenuItem.FieldEnum;
    /**
    * The record\'s ID on the partner system. For example, the item id in case type is ITEM.
    */
    'id': string;
    /**
    * The record\'s price in minor unit format.
    */
    'price'?: number;
    /**
    * The record\'s availableStatus.   Note: In order to set an item as \"UNAVAILABLE\", it is required to update both the `availableStatus` and `maxStock` fields, whereby the `maxStock` value should be set to 0. 
    */
    'availableStatus'?: UpdateMenuItem.AvailableStatusEnum;
    /**
    * Available stocks under inventory for this item. Auto reduce when there is order placed for this item.  Note: It is necessary to set `maxStock` to 0 if the `availableStatus` of the item is \"UNAVAILABLE\". Item will be set to \"AVAILABLE\" if `maxStock` > 0. 
    */
    'maxStock'?: number;
    /**
    * Price configuration (in minor unit) for different service, order type and channel combination. If a service type does not have a specified price, it will utilize the default price of the item. 
    */
    'advancedPricings'?: Array<UpdateAdvancedPricing>;
    /**
    * Purchasability is set to true by default for all service type, unless it is explicitly set to false. Modifier will reuse it’s item’s purchasability. 
    */
    'purchasabilities'?: Array<UpdatePurchasability>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "UpdateMenuItem.FieldEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "availableStatus",
            "baseName": "availableStatus",
            "type": "UpdateMenuItem.AvailableStatusEnum"
        },
        {
            "name": "maxStock",
            "baseName": "maxStock",
            "type": "number"
        },
        {
            "name": "advancedPricings",
            "baseName": "advancedPricings",
            "type": "Array<UpdateAdvancedPricing>"
        },
        {
            "name": "purchasabilities",
            "baseName": "purchasabilities",
            "type": "Array<UpdatePurchasability>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateMenuItem.attributeTypeMap;
    }
}

export namespace UpdateMenuItem {
    export enum FieldEnum {
        Item = <any> 'ITEM',
        UnknownDefaultOpenApi = <any> '11184809'
    }
    export enum AvailableStatusEnum {
        Available = <any> 'AVAILABLE',
        Unavailable = <any> 'UNAVAILABLE',
        Unavailabletoday = <any> 'UNAVAILABLETODAY',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
