// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object contain update store delivery hour response
*/
export class UpdateDeliveryHourResponse {
    /**
    * Error message when updating store delivery hour. `null` indicates no error.
    */
    'errorReasons'?: Array<UpdateDeliveryHourResponse.ErrorReasonsEnum>;
    /**
    * Total active order for the day.
    */
    'orderCount': number;
    /**
    * Total scheduled order during store close period.
    */
    'scheduledOrderCount': number;
    /**
    * Indicate the store status after updating delivery hours.
    */
    'closeImmediately': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errorReasons",
            "baseName": "errorReasons",
            "type": "Array<UpdateDeliveryHourResponse.ErrorReasonsEnum>"
        },
        {
            "name": "orderCount",
            "baseName": "orderCount",
            "type": "number"
        },
        {
            "name": "scheduledOrderCount",
            "baseName": "scheduledOrderCount",
            "type": "number"
        },
        {
            "name": "closeImmediately",
            "baseName": "closeImmediately",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateDeliveryHourResponse.attributeTypeMap;
    }
}

export namespace UpdateDeliveryHourResponse {
    export enum ErrorReasonsEnum {
        ClosingHoursIneffective = <any> 'ClosingHoursIneffective',
        ForceUpdated = <any> 'ForceUpdated',
        PendingScheduledOrders = <any> 'PendingScheduledOrders',
        PendingOrders = <any> 'PendingOrders',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
