// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Object contain update store dine-in hour response
*/
export class UpdateDineInHourResponse {
    /**
    * Error message when updating store dine-in hour. `null` indicates no error.
    */
    'errorReasons'?: Array<string> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errorReasons",
            "baseName": "errorReasons",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateDineInHourResponse.attributeTypeMap;
    }
}

