// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StoreHour } from './storeHour';

/**
* Object contains store delivery hours.
*/
export class UpdateDeliveryHourRequest {
    'openingHour': StoreHour;
    /**
    * To enable force update store delivery hours. Error will be returned if set to false while there is ongoing order.
    */
    'force': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "openingHour",
            "baseName": "openingHour",
            "type": "StoreHour"
        },
        {
            "name": "force",
            "baseName": "force",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateDeliveryHourRequest.attributeTypeMap;
    }
}

