// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UpdateAdvancedPricing } from './updateAdvancedPricing';

/**
* Information about the GrabFood client updating their food menu. 
*/
export class UpdateMenuModifier {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID': string;
    /**
    * The record type that you want to update.
    */
    'field': UpdateMenuModifier.FieldEnum;
    /**
    * The record\'s ID on the partner system. For example, the modifier id in case type is MODIFIER.
    */
    'id': string;
    /**
    * The record\'s price in minor unit format.
    */
    'price'?: number;
    /**
    * **Only required when updating modifiers.** The record\'s name. Used as identifier to locate the correct record.
    */
    'name': string;
    /**
    * The record\'s availableStatus.
    */
    'availableStatus'?: UpdateMenuModifier.AvailableStatusEnum;
    /**
    * Allows the modifier\'s price to be explicitly set as zero. Possible values are as follows:   * `isFree` && `price == 0` sets the modifier\'s price to zero.   * `isFree` && `price > 0` returns an error message that \"price cannot be set to > 0, if modifier is free”.   * `!isFree` && `price > 0` sets the modifier\'s price to the defined price.   * `!isFree` && `price == 0` does not update the modifier\'s price and reuses the existing price. 
    */
    'isFree'?: boolean;
    /**
    * Price configuration (in minor unit) for different service, order type and channel combination. If a service type does not have a specified price, it will utilize the default price of the item. 
    */
    'advancedPricings'?: Array<UpdateAdvancedPricing>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "UpdateMenuModifier.FieldEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "availableStatus",
            "baseName": "availableStatus",
            "type": "UpdateMenuModifier.AvailableStatusEnum"
        },
        {
            "name": "isFree",
            "baseName": "isFree",
            "type": "boolean"
        },
        {
            "name": "advancedPricings",
            "baseName": "advancedPricings",
            "type": "Array<UpdateAdvancedPricing>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateMenuModifier.attributeTypeMap;
    }
}

export namespace UpdateMenuModifier {
    export enum FieldEnum {
        Modifier = <any> 'MODIFIER',
        UnknownDefaultOpenApi = <any> '11184809'
    }
    export enum AvailableStatusEnum {
        Available = <any> 'AVAILABLE',
        Unavailable = <any> 'UNAVAILABLE',
        Unavailabletoday = <any> 'UNAVAILABLETODAY',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
