// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateAdvancedPricing {
    /**
    * Available service type.
    */
    'key'?: UpdateAdvancedPricing.KeyEnum;
    /**
    * Price in minor unit.
    */
    'price'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "UpdateAdvancedPricing.KeyEnum"
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UpdateAdvancedPricing.attributeTypeMap;
    }
}

export namespace UpdateAdvancedPricing {
    export enum KeyEnum {
        DeliveryOnDemandGrabApp = <any> 'Delivery_OnDemand_GrabApp',
        DeliveryScheduledGrabApp = <any> 'Delivery_Scheduled_GrabApp',
        SelfPickUpOnDemandGrabApp = <any> 'SelfPickUp_OnDemand_GrabApp',
        DineInOnDemandGrabApp = <any> 'DineIn_OnDemand_GrabApp',
        DeliveryOnDemandStoreFront = <any> 'Delivery_OnDemand_StoreFront',
        DeliveryScheduledStoreFront = <any> 'Delivery_Scheduled_StoreFront',
        SelfPickUpOnDemandStoreFront = <any> 'SelfPickUp_OnDemand_StoreFront',
        UnknownDefaultOpenApi = <any> '11184809'
    }
}
