// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SpecialOpeningHour } from './specialOpeningHour';

/**
* Object contains store special hours.
*/
export class UpdateSpecialHourRequest {
    /**
    * An array of objects contain store special hours. Max. 3 array elements.
    */
    'specialOpeningHours': Array<SpecialOpeningHour>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "specialOpeningHours",
            "baseName": "specialOpeningHours",
            "type": "Array<SpecialOpeningHour>"
        }    ];

    static getAttributeTypeMap() {
        return UpdateSpecialHourRequest.attributeTypeMap;
    }
}

