// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CampaignConditions } from './campaignConditions';
import { CampaignDiscount } from './campaignDiscount';
import { CampaignQuotas } from './campaignQuotas';

/**
* This request updates a campaign for your GrabFood store. 
*/
export class UpdateCampaignRequest {
    /**
    * The merchant\'s ID that is in GrabFood\'s database.
    */
    'merchantID'?: string;
    /**
    * The campaign\'s name.
    */
    'name'?: string;
    'quotas'?: CampaignQuotas;
    'conditions'?: CampaignConditions;
    'discount'?: CampaignDiscount;
    /**
    * Specify the tag for custom bundle offer campaign. Only whitelisted partner is supported as of now.
    */
    'customTag'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "merchantID",
            "baseName": "merchantID",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "quotas",
            "baseName": "quotas",
            "type": "CampaignQuotas"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "CampaignConditions"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "CampaignDiscount"
        },
        {
            "name": "customTag",
            "baseName": "customTag",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateCampaignRequest.attributeTypeMap;
    }
}

