// Copyright 2024 Grabtaxi Holdings PTE LTE (GRAB), All rights reserved.
// Use of this source code is governed by an MIT-style license that can be found in the LICENSE file

/*
 * GrabFood
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WorkingHourDay } from './workingHourDay';

/**
* A JSON object that describes the workingHour for each day.
*/
export class WorkingHour {
    'sun'?: WorkingHourDay;
    'mon'?: WorkingHourDay;
    'tue'?: WorkingHourDay;
    'wed'?: WorkingHourDay;
    'thu'?: WorkingHourDay;
    'fri'?: WorkingHourDay;
    'sat'?: WorkingHourDay;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sun",
            "baseName": "sun",
            "type": "WorkingHourDay"
        },
        {
            "name": "mon",
            "baseName": "mon",
            "type": "WorkingHourDay"
        },
        {
            "name": "tue",
            "baseName": "tue",
            "type": "WorkingHourDay"
        },
        {
            "name": "wed",
            "baseName": "wed",
            "type": "WorkingHourDay"
        },
        {
            "name": "thu",
            "baseName": "thu",
            "type": "WorkingHourDay"
        },
        {
            "name": "fri",
            "baseName": "fri",
            "type": "WorkingHourDay"
        },
        {
            "name": "sat",
            "baseName": "sat",
            "type": "WorkingHourDay"
        }    ];

    static getAttributeTypeMap() {
        return WorkingHour.attributeTypeMap;
    }
}

